############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Products"
url = "products/"
weight = 3

[[main]]
name = "Services"
url = "services/"
weight = 3

[[main]]
weight = 4
name = "Other"
hasChildren = true

[[main]]
parent = "Other"
name = "Blog"
url = "blog/"

[[main]]
parent = "Other"
name = "Contact"
url = "contact/"

[[main]]
parent = "Other"
name = "Categories"
url = "categories/"



# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Products"
url = "products/"
weight = 2

[[footer]]
name = "Services"
url = "services/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 4

