############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

#[[main]]
#name = "Services"
#url = "elements/"
#weight = 3

[[main]]
weight = 4
name = "Other"
hasChildren = true

[[main]]
parent = "Other"
name = "Blog"
url = "blog/"

[[main]]
parent = "Other"
name = "Contact"
url = "contact/"

[[main]]
parent = "Other"
name = "Categories"
url = "categories/"



# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Services"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
